=== kishan-dev-07/TechThreads/TechThreads.dtd
<!ELEMENT QASystem (User, Question, Answer, Post, Comment, Tag, Vote, Badge, ActivityLog)>
<!ELEMENT User (UserID, Name, Email, Password, About, JoinedOn)>
<!ELEMENT UserID (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Password (#PCDATA)>
<!ELEMENT About (#PCDATA)>
<!ELEMENT JoinedOn (#PCDATA)>

<!ELEMENT Question (QuestionID, QuestionTitle, QuestionBody, QuestionTags, AskedOn)>
<!ELEMENT QuestionID (#PCDATA)>
<!ELEMENT QuestionTitle (#PCDATA)>
<!ELEMENT QuestionBody (#PCDATA)>
<!ELEMENT QuestionTags (#PCDATA)>
<!ELEMENT AskedOn (#PCDATA)>

<!ELEMENT Answer (AnswerID, AnswerBody, AnsweredOn)>
<!ELEMENT AnswerID (#PCDATA)>
<!ELEMENT AnswerBody (#PCDATA)>
<!ELEMENT AnsweredOn (#PCDATA)>

<!ELEMENT Post (PostID, PostTitle, PostFile, PostedOn)>
<!ELEMENT PostID (#PCDATA)>
<!ELEMENT PostTitle (#PCDATA)>
<!ELEMENT PostFile (#PCDATA)>
<!ELEMENT PostedOn (#PCDATA)>

<!ELEMENT Comment (CommentID, CommentBody, CommentedOn)>
<!ELEMENT CommentID (#PCDATA)>
<!ELEMENT CommentBody (#PCDATA)>
<!ELEMENT CommentedOn (#PCDATA)>

<!ELEMENT Tag (TagID, TagName, TagDescription)>
<!ELEMENT TagID (#PCDATA)>
<!ELEMENT TagName (#PCDATA)>
<!ELEMENT TagDescription (#PCDATA)>

<!ELEMENT Vote (VoteID, VoteType, VotedOn)>
<!ELEMENT VoteID (#PCDATA)>
<!ELEMENT VoteType (#PCDATA)>
<!ELEMENT VotedOn (#PCDATA)>

<!ELEMENT Badge (BadgeID, BadgeName, Description)>
<!ELEMENT BadgeID (#PCDATA)>
<!ELEMENT BadgeName (#PCDATA)>
<!ELEMENT Description (#PCDATA)>

<!ELEMENT ActivityLog (LogID, ActivityType, LoggedOn)>
<!ELEMENT LogID (#PCDATA)>
<!ELEMENT ActivityType (#PCDATA)>
<!ELEMENT LoggedOn (#PCDATA)>

=== kishan-dev-07/TechThreads/TechThreads.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="TechThreads.xsl"?>
<!DOCTYPE QASystem SYSTEM "TechThreads.dtd">
<QASystem >
    <User>
        <UserID>U001</UserID>
        <Name>John Doe</Name>
        <Email>john.doe@example.com</Email>
        <Password>password123</Password>
        <About>A software developer.</About>
        <JoinedOn>2023-01-15</JoinedOn>
    </User>
    <Question>
        <QuestionID>Q001</QuestionID>
        <QuestionTitle>How to validate XML?</QuestionTitle>
        <QuestionBody>What are the best practices to validate an XML file?</QuestionBody>
        <QuestionTags>XML, Validation</QuestionTags>
        <AskedOn>2023-02-10</AskedOn>
    </Question>
    <Answer>
        <AnswerID>A001</AnswerID>
        <AnswerBody>Use DTD or XSD to validate XML files.</AnswerBody>
        <AnsweredOn>2023-02-11</AnsweredOn>
    </Answer>
    <Post>
        <PostID>P001</PostID>
        <PostTitle>XML Validation Post</PostTitle>
        <PostFile>https://example.com/postfile.xml</PostFile>
        <PostedOn>2023-02-12</PostedOn>
    </Post>
    <Comment>
        <CommentID>C001</CommentID>
        <CommentBody>This is a comment.</CommentBody>
        <CommentedOn>2023-02-13</CommentedOn>
    </Comment>
    <Tag>
        <TagID>T001</TagID>
        <TagName>XML</TagName>
        <TagDescription>Questions related to XML.</TagDescription>
    </Tag>
    <Vote>
        <VoteID>V001</VoteID>
        <VoteType>upvote</VoteType>
        <VotedOn>2023-02-14</VotedOn>
    </Vote>
    <Badge>
        <BadgeID>B001</BadgeID>
        <BadgeName>XML Expert</BadgeName>
        <Description>Awarded for expertise in XML.</Description>
    </Badge>
    <ActivityLog>
        <LogID>L001</LogID>
        <ActivityType>login</ActivityType>
        <LoggedOn>2023-02-15</LoggedOn>
    </ActivityLog>
</QASystem>
